<?php

/**
 * @file
 * Contains editorial_improvements.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function editorial_improvements_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the editorial_improvements module.
    case 'help.page.editorial_improvements':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Improvements for editorial workflows') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_editor_js_settings_alter
 * @param array $settings
 */
function editorial_improvements_editor_js_settings_alter(array &$settings) {
  if (empty($settings['editor']['formats'])) {
    return;
  }

  foreach ($settings['editor']['formats'] as $format => $setting) {
    // http://docs.ckeditor.com/#!/api/CKEDITOR.config-cfg-skin
    // When setting config.skin it is possible to specify custom skin location
    // after a comma.
    if ($setting['editor'] == 'ckeditor') {
      $settings['editor']['formats'][$format]['editorSettings']['skin'] = 'bootstrapck,' . base_path() . 'libraries/ckeditor_skin_bootstrap/';
    }
  }
}
